spring:
  flyway:
    locations: "classpath:migrations"
  datasource:
    url: "jdbc:postgresql://${TAZB_HOST:localhost}:5432/tazbdb"
    username: ${TAZB_USER:tazbuser}
    password: ${TAZB_PASSWORD:tazbpassword}
  h2:
    console:
      enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace
