CREATE COLLATION IF NOT EXISTS case_insensitive (provider = icu, locale = '@colStrength=secondary', deterministic = false);

CREATE TABLE IF NOT EXISTS monthly_budgets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  budget_date DATE UNIQUE NOT NULL
);

ALTER TABLE monthly_budgets OWNER TO tazbuser;

CREATE TABLE IF NOT EXISTS monthly_category_plans (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  monthly_budget_id BIGINT,
  transaction_category_id BIGINT,
  planned_amount NUMERIC(19,4),
  UNIQUE (monthly_budget_id, transaction_category_id)
);

ALTER TABLE monthly_category_plans OWNER TO tazbuser;

CREATE TABLE IF NOT EXISTS transaction_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(24) UNIQUE NOT NULL COLLATE case_insensitive
);

ALTER TABLE transaction_categories OWNER TO tazbuser;

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TIMESTAMP NOT NULL,
  amount NUMERIC(19,4) NOT NULL,
  description VARCHAR(500) COLLATE case_insensitive,
  monthly_budget_id BIGINT,
  transaction_category_id BIGINT
);

ALTER TABLE transactions OWNER TO tazbuser;

ALTER TABLE IF EXISTS monthly_category_plans ADD FOREIGN KEY (monthly_budget_id) REFERENCES monthly_budgets (id);

ALTER TABLE IF EXISTS monthly_category_plans ADD FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories (id);

ALTER TABLE IF EXISTS transactions ADD FOREIGN KEY (monthly_budget_id) REFERENCES monthly_budgets (id);

ALTER TABLE IF EXISTS transactions ADD FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories (id);

commit;
